name: Backend Continuous Integration

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - 'starter/backend/**'  # Only run when files in backend change

jobs:
  lint:
    runs-on: ubuntu-latest
    environment: Development Environment

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        working-directory: starter/backend
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install --dev  # Install dev dependencies if they exist

      - name: Run Lint
        working-directory: starter/backend
        run: pipenv run flake8 .  # Run flake8 linting

  test:
    runs-on: ubuntu-latest
    needs: lint  # Ensures linting completes before running tests

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        working-directory: starter/backend
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install --dev  # Install dev dependencies if they exist
          pipenv install pytest # Ensure pytest is installed

      - name: Run Tests
        working-directory: starter/backend
        run: pipenv run pytest  # Run pytest within pipenv environment

  build:
    runs-on: ubuntu-latest
    needs: [lint, test]  # Ensures lint and test jobs complete successfully

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Build Docker Image
        working-directory: starter/backend
        run: docker build -t mp-backend:latest .