name: Frontend Continuous Deployment

on:
  push:
    branches:
      - main
    paths:
      - 'starter/frontend/**'  # Only run when files in frontend change
  workflow_dispatch:  # Allows manual triggering

env:
  AWS_REGION: us-west-1
  ECR_REPOSITORY: movie-picture-frontend  # Make sure this matches your ECR repository name for the frontend

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker Image
        working-directory: starter/frontend
        run: |
          docker build -t frontend-app:$GITHUB_SHA \
          --build-arg REACT_APP_MOVIE_API_URL=${{ secrets.REACT_APP_MOVIE_API_URL }} .
          
  push-to-ecr:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Tag Docker Image
        run: docker tag frontend-app:$GITHUB_SHA 736618489805.dkr.ecr.us-west-1.amazonaws.com/${{ env.ECR_REPOSITORY }}:$GITHUB_SHA

      - name: Push Docker Image
        run: docker push 736618489805.dkr.ecr.us-west-1.amazonaws.com/${{ env.ECR_REPOSITORY }}:$GITHUB_SHA

  deploy:
    needs: push-to-ecr
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1

      - name: Update kubeconfig for EKS
        run: aws eks update-kubeconfig --name cluster --region us-west-1

      - name: Deploy to Kubernetes
        run: |
          kubectl set image deployment/frontend frontend=736618489805.dkr.ecr.us-west-1.amazonaws.com/${{ env.ECR_REPOSITORY }}:$GITHUB_SHA
          kubectl rollout status deployment/frontend